In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
data = pd.read_csv('salesdata.csv')

In [6]:
data

     Region  Manager   SalesMan          Item  Units  Unit_price  Sale_amt
0      East   Martha  Alexander    Television     95      1198.0  113810.0
1   Central  Hermann     Shelli  Home Theater     50       500.0   25000.0
2   Central  Hermann       Luis    Television     36      1198.0   43128.0
3   Central  Timothy      David    Cell Phone     27       225.0    6075.0
4      West  Timothy    Stephen    Television     56      1198.0   67088.0
5      East   Martha  Alexander  Home Theater     60       500.0   30000.0
6   Central   Martha     Steven    Television     75      1198.0   89850.0
7   Central  Hermann       Luis    Television     90      1198.0  107820.0
8      West  Douglas    Michael    Television     32      1198.0   38336.0
9      East   Martha  Alexander  Home Theater     60       500.0   30000.0
10  Central  Hermann      Sigal    Television     90      1198.0  107820.0
11     East   Martha      Diana  Home Theater     29       500.0   14500.0
12     East  Douglas      Karen  Home Theater     81       500.0   40500.0
13     East   Martha  Alexander    Television     35      1198.0   41930.0
14  Central  Douglas       John          Desk      2       125.0     250.0
15     East   Martha  Alexander   Video Games     16        58.5     936.0
16  Central  Hermann      Sigal  Home Theater     28       500.0   14000.0
17     East   Martha  Alexander    Cell Phone     64       225.0   14400.0
18     East  Douglas      Karen    Cell Phone     15       225.0    3375.0
19  Central  Hermann     Shelli   Video Games     96        58.5    5616.0
20  Central  Douglas       John    Television     67      1198.0   80266.0
21     East  Douglas      Karen   Video Games     74        58.5    4329.0
22  Central  Timothy      David  Home Theater     46       500.0   23000.0
23  Central  Douglas       John  Home Theater     87       500.0   43500.0
24     East   Martha  Alexander  Home Theater      4       500.0    2000.0
25     West  Timothy    Stephen  Home Theater      7       500.0    3500.0
26  Central  Hermann       Luis   Video Games     50        58.5    2925.0
27  Central   Martha     Steven    Television     66      1198.0   79068.0
28     East   Martha      Diana    Cell Phone     96       225.0   21600.0
29  Central  Timothy      David    Television     53      1198.0   63494.0
30  Central  Timothy      David  Home Theater     80       500.0   40000.0
31  Central  Hermann     Shelli          Desk      5       125.0     625.0
32     East   Martha  Alexander   Video Games     62        58.5    3627.0
33  Central  Hermann      Sigal   Video Games     55        58.5    3217.5
34  Central  Hermann     Shelli   Video Games     42        58.5    2457.0
35     West  Timothy    Stephen          Desk      3       125.0     375.0
36  Central  Timothy      David    Television      7      1198.0    8386.0
37     West  Timothy    Stephen    Cell Phone     76       225.0   17100.0
38     West  Douglas    Michael  Home Theater     57       500.0   28500.0
39  Central   Martha     Steven    Television     14      1198.0   16772.0
40  Central  Hermann       Luis  Home Theater     11       500.0    5500.0
41  Central  Hermann       Luis  Home Theater     94       500.0   47000.0
42  Central    Marth     Steven  Home Theater     28       500.0   14000.0

In [7]:
data.head()

    Region  Manager   SalesMan          Item  Units  Unit_price  Sale_amt
0     East   Martha  Alexander    Television     95      1198.0  113810.0
1  Central  Hermann     Shelli  Home Theater     50       500.0   25000.0
2  Central  Hermann       Luis    Television     36      1198.0   43128.0
3  Central  Timothy      David    Cell Phone     27       225.0    6075.0
4     West  Timothy    Stephen    Television     56      1198.0   67088.0

In [8]:
data.tail()

     Region  Manager SalesMan          Item  Units  Unit_price  Sale_amt
38     West  Douglas  Michael  Home Theater     57       500.0   28500.0
39  Central   Martha   Steven    Television     14      1198.0   16772.0
40  Central  Hermann     Luis  Home Theater     11       500.0    5500.0
41  Central  Hermann     Luis  Home Theater     94       500.0   47000.0
42  Central    Marth   Steven  Home Theater     28       500.0   14000.0

In [9]:
data.describe()

           Units   Unit_price       Sale_amt
count  43.000000    43.000000      43.000000
mean   49.325581   581.011628   30364.546512
std    30.078248   442.285830   32424.588323
min     2.000000    58.500000     250.000000
25%    27.500000   225.000000    3978.000000
50%    53.000000   500.000000   17100.000000
75%    74.500000  1198.000000   42529.000000
max    96.000000  1198.000000  113810.000000

In [10]:
data.describe().T

,count,mean,std,min,25%,50%,75%,max
Units,43.0,49.325581,30.078248,2.0,27.5,53.0,74.5,96.0
Unit_price,43.0,581.011628,442.285830,58.5,225.0,500.0,1198.0,1198.0
Sale_amt,43.0,30364.546512,32424.588323,250.0,3978.0,17100.0,42529.0,113810.0

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Region      43 non-null     object
 1   Manager     43 non-null     object
 2   SalesMan    43 non-null     object
 3   Item        43 non-null     object
 4   Units       43 non-null     int64
 5   Unit_price  43 non-null     float64
 6   Sale_amt    43 non-null     float64
dtypes: float64(2), int64(1), object(4)
memory usage: 2.5+ KB

In [12]:
data["Region"].value_counts()

Region
Central    24
East       13
West        6
Name: count, dtype: int64

In [17]:
data["Manager"].value_counts()

Manager
Martha     13
Hermann    12
Timothy     9
Douglas     8
Marth       1
Name: count, dtype: int64

In [16]:
data["Manager"].unique()

array(['Martha', 'Hermann', 'Timothy', 'Douglas', 'Marth'], dtype=object)

In [18]:
data["Manager"].nunique()

5

In [21]:
data.isna()

    Region  Manager  SalesMan   Item  Units  Unit_price  Sale_amt
0    False    False     False  False  False       False     False
1    False    False     False  False  False       False     False
2    False    False     False  False  False       False     False
3    False    False     False  False  False       False     False
4    False    False     False  False  False       False     False
5    False    False     False  False  False       False     False
6    False    False     False  False  False       False     False
7    False    False     False  False  False       False     False
8    False    False     False  False  False       False     False
9    False    False     False  False  False       False     False
10   False    False     False  False  False       False     False
11   False    False     False  False  False       False     False
12   False    False     False  False  False       False     False
13   False    False     False  False  False       False     False
14   False    False     False  False  False       False     False
15   False    False     False  False  False       False     False
16   False    False     False  False  False       False     False
17   False    False     False  False  False       False     False
18   False    False     False  False  False       False     False
19   False    False     False  False  False       False     False
20   False    False     False  False  False       False     False
21   False    False     False  False  False       False     False
22   False    False     False  False  False       False     False
23   False    False     False  False  False       False     False
24   False    False     False  False  False       False     False
25   False    False     False  False  False       False     False
26   False    False     False  False  False       False     False
27   False    False     False  False  False       False     False
28   False    False     False  False  False       False     False
29   False    False     False  False  False       False     False
30   False    False     False  False  False       False     False
31   False    False     False  False  False       False     False
32   False    False     False  False  False       False     False
33   False    False     False  False  False       False     False
34   False    False     False  False  False       False     False
35   False    False     False  False  False       False     False
36   False    False     False  False  False       False     False
37   False    False     False  False  False       False     False
38   False    False     False  False  False       False     False
39   False    False     False  False  False       False     False
40   False    False     False  False  False       False     False
41   False    False     False  False  False       False     False
42   False    False     False  False  False       False     False

In [22]:
data.isna().sum()

Region        0
Manager       0
SalesMan      0
Item          0
Units         0
Unit_price    0
Sale_amt      0
dtype: int64

In [23]:
data.duplicated().sum()

np.int64(1)

In [24]:
data.drop_duplicates(inplace=True)

In [26]:
data.duplicated().sum()

np.int64(0)